mysite/hoadues/urls.py
from django.urls import path, re_path
from . import views

app_name = 'hoadues'

urlpatterns = [
    path('login_user', views.login_user, name='login_user'),
    path('member_page', views.member_page, name='member_page'),
    path('logout_user', views.logout_user, name='logout_user'),
    path('check_out', views.check_out, name='check_out'),
    path('postcheck_out', views.postcheck_out, name='postcheck_out'),
    
    path('', views.index, name='index'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

urlpatterns = [
    #path('hoadues/', include('hoadues.urls')),
    path('hoadues/', include('hoadues.urls')),
    # changes login_url  default
    #account/login -> hoadues/login_user
    re_path(r'login/$',include('hoadues.urls'), name="login_user"),
    path('hoadues/', include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]


##urlpatterns = [
    #path('polls/', views.polls, name='polls'),
# ex: /polls/
    ##path ('', views.index, name="index"),
# ex: /polls/5/
    ##path('<int:question_id>/', views.detail, name='detail'),
# ex: /polls/5/results/
    ##path ('<int:question_id>/results', views.results, name='results'),
# ex: /polls/5/vote/
    ##path ('<int:question_id>/vote', views.vote , name="vote"),

##]

mysite/hoadues/models.py
from django.db import models
from datetime import datetime

#Custom's User without Username
from django.contrib.auth.models import AbstractUser
#from django.utils.translation import ugettext_lazy as _

#Let Manager Know
from django.contrib.auth.models import BaseUserManager



#Class Managger
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user



    def _create_user(self, email, password,  **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)




class User(AbstractUser):
    """User model."""

#Remove User Name Field
    username = None
#Make the email field required and unique
    email = models.EmailField(('email address'), unique=True)
#Going to Email to replace username Field
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

#Let the Mangager know
    objects = UserManager() ## This is the new line in the User model. ##


class Address(models.Model):
    lot = models.IntegerField()
    street_num = models.IntegerField()
    street = models.CharField(max_length=200)
    #owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return "Lot: "+str(self.lot)







# Create your models here.
# Create your models here.
class Bill(models.Model):
    dscpt_text=models.CharField(max_length=200)
    issue_date = models.DateField(auto_now_add= True, verbose_name=("Creation date"))
    due_date = models.DateField(verbose_name=("Due date"))
    amt = models.DecimalField(decimal_places=2, max_digits=20)
    paid = models.BooleanField(default=False)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.dscpt_text + " " + self.issue_date.strftime("%m/%d/%Y, %H:%M:%S") + " " + self.due_date.strftime("%m/%d/%Y, %H:%M:%S") + " " + str(self.amt)

mysite/hoadues/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from .models import  Address , Bill
import stripe

from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt


import stripe
stripe.api_key = 'sk_test_51MgxbRDasDOaJtxccHA7mDET3F449MUNLtbsIjdwOPW2KgZSvmB9CoHqkd0Ggpo6rNt9yIZtwGDXKEcGSXfnwHJP00W3DrZqt2'

YOUR_DOMAIN="http://localhost:8000"


# Create your views here.

def login_user( request):
    if request.method =='POST':
        email = request.POST['email']
        password = request.POST['password']
        print(email)
        print(password)
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
        # Redirect to a success page.
            print("MADDDDDE IT!!!!")
            return redirect('hoadues:member_page')
        else:
            # Return an 'invalid login' error message
            print("ERROROROROROROROROR!")
            return  render ( request, 'hoadues/login.html')
    else:
         return  render ( request, 'hoadues/login.html')

def logout_user(request):
    logout(request)
    return  render ( request, 'hoadues/login.html')

def index( request):
    return  render ( request, 'hoadues/login.html')


@login_required
def member_page (request ):

    bills = Bill.objects.filter(owner= request.user)
    bill = Bill.objects.filter(owner= request.user)[:1].get()
    print(bill.address)
    print(list(bills))

    sum=0
    for i in bills:
        if i.paid == False:
            sum += i.amt

    #address = Address.objects.get( owner =request.user)
    address = bill.address
    return  render ( request, 'hoadues/members.html' , {"address": address , "bills": bills , "sum": sum})

def check_out  (request):
    #get the sum of the payment
    #print("SUM " + str(sum))

    if request.method =='POST':
        sum = request.POST['SUM']
        print("hidden_sum" + str(sum))

        #multiply by *100
        sum = float(sum) * 100

        sum  = int(sum)
        print("sum_Ready" + str(sum))

        #make Intent to pay
        payment_intent = stripe.PaymentIntent.create(
        amount= sum,
        currency="usd",
        payment_method_types=["card"]

        )


        payment_method = "card"
        context={}

        if payment_method == "card":

            context['client_secret'] = payment_intent.client_secret
            #context['customer_email'] = request.user.email
            return render (request , 'hoadues/checkout.html', context)
    else:

        return member_page (request)



def postcheck_out  (request):
## POST PAID
   ## get this users bill
   print("Made it to postcheck_out!!!!!!")
   if request.method =='POST':
       print("POSTING........")
       bills = Bill.objects.filter(owner= request.user)
   ## go through all the bills
       for i in bills:
           i.paid = True
           i.save()
           print(i.paid)

       return member_page (request)
   else:

       return member_page (request)

mysite/hoadues/templates/hoadues/base.html
<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  </head>

<body>

<nav class="mb-7 navbar navbar-expand navbar  bg-primary text-white">

 <div class=" container-fluid navbar">
     <div class="row">
       <div class="col-sm">
          <a class=" text-white navbar-brand mb-0 h1" href="#"> C.G.N </a>
            <svg  class= " fa-sm" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-houses-fill" viewBox="0 0 16 16">
           <path d="M7.207 1a1 1 0 0 0-1.414 0L.146 6.646a.5.5 0 0 0 .708.708L1 7.207V12.5A1.5 1.5 0 0 0 2.5 14h.55a2.51 2.51 0 0 1-.05-.5V9.415a1.5 1.5 0 0 1-.56-2.475l5.353-5.354L7.207 1Z"/>
           <path d="M8.793 2a1 1 0 0 1 1.414 0L12 3.793V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v3.293l1.854 1.853a.5.5 0 0 1-.708.708L15 8.207V13.5a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 4 13.5V8.207l-.146.147a.5.5 0 1 1-.708-.708L8.793 2Z"/>
            </svg>
         </div>
     </div>


 <nav  class="bg-primary text-white" >

    {% if user.is_authenticated %}


      <ul class=" navbar-nav bg-primary text-white">
             <li class="nav-item ">
              <a  class=" nav-link text-white" href="
              {% url 'hoadues:logout_user' %}"> LOG OUT</a>
      </ul>


    {% else %}
      <ul class="navbar-nav">
          <li class="nav-item">
           <a  class="nav-link text-white" href="
           {%url 'hoadues:login_user' %}"> Log In </a>
          </li>
      </ul>
    {% endif %}

 </nav>

 </div>



</nav>

    <div class="container ">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

mysite/hoadues/templates/hoadues/checkout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Accept a payment</title>
    <meta name="description" content="A demo of a payment on Stripe" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />


  </head>
  <script src="https://js.stripe.com/v3/"></script>
  <body>


    <!-- Display a payment form -->
    <form action="{% url 'hoadues:postcheck_out' %}" method="post"  id="payment-form" data-secret="{{ client_secret }}" >
      {% csrf_token %}
      <!-- <div id="link-authentication-element">
      Stripe.js injects the Link Authentication Element-->
      <!--
      </div>
       -->
      <div id="payment-element">
        <!--Stripe.js injects the Payment Element-->
      </div>



      <div id="card-element" >
        <!--Stripe.js injects the card Element-->
      </div>

      <button id="submit_new">
         <div class="spinner hidden" id="spinner"></div>
        <span id="button-text">Pay now</span>
      </button>


      <div id="payment-message" class="hidden"></div>
    </form>


      <link rel="stylesheet" href= "{% static 'hoadues/css/checkout.css'  %}" />
      <script src="{% static 'hoadues/js/checkout.js'  %}" ></script>

  </body>

</html>

mysite/hoadues/templates/hoadues/login.html
{% extends 'hoadues/base.html' %}

{% block content %}

<form  class= " mt-5 h-100 align-middle w-100"action="{% url 'hoadues:login_user' %}" method="POST">
  {% csrf_token %}
  <!-- Email input -->
<div class= "d-flex justify-content-center" >
    <label class="form-label" for="form2Example1"  > Email: </label>
  </div>

  <div class= "d-flex justify-content-center" >
      <div class="mb-3 form-group mb-0 ">
     <input type="email" id="form2Example1" placeholder="Email address" name="email"/>
   </div>
  </div>

<div class= "d-flex justify-content-center" >
<label class="form-label" for="form2Example2">Password: </label>
  </div>

  <div class= "d-flex justify-content-center" >
  <!-- Password input -->
  <div class="form-group mb-0 ">
    <input  class ="mb-3" type="password" id="form2Example2" placeholder="Password" name="password"  />
    <label class="form-label" for="form2Example2"></label>

  </div>
</div>







<div class= "d-flex justify-content-center" >
  <!-- Submit button -->
  <button type="submit" class="btn btn-primary ">Log In</button>
</div>



<div class= "d-flex justify-content-center" >

  <!-- 2 column grid layout for inline styling -->

      <!-- Checkbox -->
      <!-- <div class="form-check">
        <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
        <label class="form-check-label" for="form2Example31"> Remember me </label>
      </div>
    </div>
  -->

      <!-- Simple link -->
      <a href="#!">Forgot password?</a>





</div>
{% endblock %}

</form>

mysite/hoadues/templates/hoadues/members.html
{% extends 'hoadues/base.html' %}

{% block content %}


<section  class="pb-4"
  <div class="bg-white border rounded-5"
    <section class="w-100 p-4 justify-content-center">
      <div class="card" >
        <div class="card-body">
            <div class="container mb-5 mt-3">
              <div class="row d-flex align-items-baseline">
                <div class="col-xl-9">
                    <p style="color: #7e8d9f; font-size: 20px;">
                      "Invoice >>" <strong> ID: #123-123</strong>
                    </p>
                 </div>

                 <div class="col-xl-3 float end">
                 <a class="btn btn-light text-capitalized border-0 ripple-surface-dark " data-mdb-ripple color="dark"

                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-printer" viewBox="0 0 16 16">
                          <path d="M2.5 8a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
                          <path d="M5 1a2 2 0 0 0-2 2v2H2a2 2 0 0 0-2 2v3a2 2 0 0 0 2 2h1v1a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2v-1h1a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2h-1V3a2 2 0 0 0-2-2H5zM4 3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v2H4V3zm1 5a2 2 0 0 0-2 2v1H2a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-1v-1a2 2 0 0 0-2-2H5zm7 2v3a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1z"/>
                          </svg>



                          <i class="far fa-file-pdf text-danger"></i>
                            "Export"
                  </a>
                </div>
                <hr>

              <div class="container "
                  <div class="col-md-12 w-100">
                    <div class="text-center">
                        <i class="fab fa-mdb fa-4x ms-0" style="color:#5d9fc5 ;"></i>
                        <p class="pt-0">MDBootstrap.com</p>
                    </div>
                  </div>


              <div class="row  w-100" >
                <ul class="list-unstyled">
                    <li class="text-muted">To: <span style="color:#5d9fc5 ;"> {{  request.user.get_full_name }}</span></li>
                    <li class="text-muted">{{ address.street_num }} </li>
                    <li class="text-muted">{{ address.street }} </li>
                    <li class="text-muted">Indianapolis , IN  46234</li>
                    <li class="text-muted">Lot: {{ address.lot }}</li>
                    <li class="text-muted"><i class="fas fa-phone"></i> 123-456-789</li>
                </ul>
             </div>

             <div  class="row w-100">

                <p class="text-muted">Invoice</p>

            </div>


             <ul class="list-unstyled">

                <li class="text-muted" </li>
                  <i class="fas fa-circle" style="color:#84B0CA ;"></i>
                  <span class="fw-bold">ID:</span> #123-456
                </li>

                <li class="text-muted">
                <i class="fas fa-circle" style="color:#84B0CA ;"></i>
                <span class="fw-bold">ID:</span> #123-456
                </li>

                <li class="text-muted">
                  <i class="fas fa-circle" style="color:#84B0CA ;"></i>
                  <span class="me-1 fw-bold">Status:</span>
                  <span class="badge bg-warning text-black fw-bold">  Unpaid</span>
                  </li>

                  <div class="row my-2 mx-1 justify-content-center">

                  <table class="table table-striped table-borderless">

                    <thead style="background-color:#84B0CA ;" class="text-white">
                      <tr>
                        <th scope="col">Date</th>
                        <th scope="col">Description</th>
                        <th scope="col">Amount</th>
                        <th scope="col">PAID</th>
                      </tr>
                    </thead>

                    <tbody>

                 {% for bill in bills %}
                      <tr>
                        <td> {{ bill.issue_date }} </td>
                        <td> {{ bill.dscpt_text }} </td>
                        <td>{{ bill.amt }}</td>
                        <td>{{ bill.paid }}</td>
                      </tr>
                  {% endfor %}


                    </tbody>

                  </table>
                </div>


                <div class="row">
                <div class="col-xl-8">
                  <p class="ms-3">Add additional notes and payment information</p>

                </div>
                <div class="col-xl-4">
                  <ul class="list-unstyled text-right">
                    <li class="text-muted ms-3 "><span class="text-black me-4">SubTotal:</span><b> {{ sum }} </b> </li>
                  </ul>
                  <p class="text-black float-start"><span class="text-black me-4">Amount: </span><span style="font-size: 25px;">{{ sum }}</span></p>

                  <form id="payment-form"  action="{% url 'hoadues:check_out' %}" method="post" }}>
                {% csrf_token %}
                <button id="submit_button">
                     <div class="spinner hidden" id="spinner"></div>
                     <input type="hidden" name="SUM" value= {{ sum }} />
                    <span id="button-text">Pay now</span>
                  </button>
                 </form>

                </div>
              </div>








{% endblock %}